networks:
  vastsea-sso:
    name: vastsea-sso

services:
  frontend:
    image: vastsea/vastsea-sso-frontend
    container_name: vastsea-sso-frontend
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/frontend:/etc/nginx/logs
    networks:
      - vastsea-sso
    depends_on:
      - backend
  backend:
    image: vastsea/vastsea-sso-backend
    container_name: vastsea-sso-backend
    restart: always
    volumes:
      - ./config/keys:/app/keys
      - ./config/backend.toml:/app/config.toml
      - ./data/backend:/app/dist/assets
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIRECT=${REDIRECT}
      - VERSION=${VERSION}
      - APP_NAME=${APP_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - vastsea-sso
    depends_on:
      - pgsql
      - redis
  pgsql:
    image: postgres
    container_name: vastsea-sso-pgsql
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - vastsea-sso
  redis:
    image: redis
    container_name: vastsea-sso-redis
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - vastsea-sso

networks:
  vastsea-sso:
    name: vastsea-sso

services:
  frontend:
    image: vastsea/vastsea-sso-frontend
    container_name: vastsea-sso-frontend
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/frontend:/etc/nginx/logs
    networks:
      - vastsea-sso
    depends_on:
      - backend
  backend:
    image: vastsea/vastsea-sso-backend
    container_name: vastsea-sso-backend
    restart: always
    volumes:
      - ./config/keys:/app/backend/keys
      - ./config/backend.toml:/app/backend/config.toml
      - ./data/backend:/app/backend/dist/assets
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIRECT=${REDIRECT}
      - VERSION=${VERSION}
      - APP_NAME=${APP_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - vastsea-sso
    depends_on:
      - pgsql
      - redis
  pgsql:
    image: postgres
    container_name: vastsea-sso-pgsql
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - vastsea-sso
  redis:
    image: redis
    container_name: vastsea-sso-redis
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - vastsea-sso
