[redis]
[redis.standalone]
host="redis"
port=6379

[email]
email="user@domain.com"
[email.transport]
host="smtp.domain.com"
port=25
secure=false
[email.transport.auth]
user="user"
pass="pass"


[cache]
[cache.ttl]
[cache.ttl.role]
list=10
info=10
tree=10
[cache.ttl.client]
secret=10
info=10
list=10
[cache.ttl.auth]
emailCode=60000
code=5000
[cache.ttl.auth.token]
access=86400000
refresh=604800000

[client]
idLen=16
secretLen=64

[captcha]
[captcha.geeTest]
gtId=""
key=""

[captcha.map]
"/account/register" = true