name: CI/CD

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-*.*"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Development Environment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - production

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.environment != '' }}
    strategy:
      matrix:
        app: [frontend, backend]
        include:
          - app: frontend
            context: ./packages/frontend
            file: ./packages/frontend/dockerfile
            needs_auth_client_id: true
          - app: backend
            context: ./packages/backend
            file: ./packages/backend/dockerfile
            needs_auth_client_id: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            vastsea/vastsea-sso-${{ matrix.app }}
            ${{ vars.REGISTRY_ADDRESS }}/${{ vars.REGISTRY_NAMESPACE }}/${{ vars.IMAGE_NAME }}-${{ matrix.app }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=test,enable=${{ github.event.inputs.environment == 'test' }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://${{ vars.REGISTRY_ADDRESS }}
          username: "${{ vars.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and push frontend
        if: matrix.app == 'frontend'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_URL=/api
            AUTH_SERVER_CLIENT_ID=${{ secrets.AUTH_SERVER_CLIENT_ID }}
      
      - name: Build and push backend
        if: matrix.app == 'backend'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy
    needs: build_docker
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.environment != '' }}
    steps:
      - name: SSH To Host
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            sudo bash ./deploy.sh ${{ github.event.inputs.environment || 'production' }}
