name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters-frontend:
    name: Run linters frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
      - name: Install dependencies
        working-directory: packages/frontend
        run: pnpm i --frozen-lockfile --prefer-offline
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: packages/frontend
          auto_fix: true
  run-linters-backend:
    name: Run linters backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
      - name: Install dependencies
        working-directory: packages/backend
        run: pnpm i --frozen-lockfile --prefer-offline
      - name: Lint libraries
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: packages/backend/libs
          auto_fix: true
      - name: Lint src
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: packages/backend/src
          auto_fix: true
      - name: Lint test
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: packages/backend/test
          auto_fix: true